version: "3.7"

services:

  rm_ticketing_node:
    image: romarius75/rm-ticketing-node-server:latest
    restart: always
    environment:
      HOST: wss.ticketing-event.com
      VIRTUAL_HOST: wss.ticketing-event.com
      LETSENCRYPT_HOST: wss.ticketing-event.com
      LETSENCRYPT_EMAIL: roman.marlovits@gmail.com
    volumes:
    - /etc/rm-ticketing/node/.config.yaml:/app/.config.yaml
    depends_on:
    - rm_ticketing_mysql

  rm_ticketing_mysql:
    image: romarius75/rm-ticketing-mysql-server:latest
    restart: always
    volumes:
    - rm_ticketing_mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Passw0Rd!

  rm_ticketing_admin:
    image: romarius75/rm-ticketing-admin:latest
    restart: always
    environment:
      HOST: admin.ticketing-event.com
      VIRTUAL_HOST: admin.ticketing-event.com
      LETSENCRYPT_HOST: admin.ticketing-event.com
      LETSENCRYPT_EMAIL: roman.marlovits@gmail.com
    volumes:
    - ./.config.yaml:/node/.config.yaml
    depends_on:
    - rm_ticketing_node

volumes:
  rm_ticketing_mysql_volume:

networks:
  default:
    external:
      name: webproxy
