version: "3.7"

services:

  rm_ticketing_mysql_server:
    image: romarius75/rm-ticketing-mysql-server:latest
    ports:
    - 3306:3306
    volumes:
    - rm_ticketing_mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Passw0Rd!

  rm_ticketing_node_server:
    image: romarius75/rm-ticketing-node-server:latest
    ports:
    - 8080:8080
    volumes:
    - ${PROJECT_PATH}\rm-ticketing-node-server\config.yaml:/app/config.yaml
    - rm_ticketing_node_volume:/files
    depends_on:
    - rm_ticketing_mysql_server

  rm_ticketing_admin:
    image: romarius75/rm-ticketing-admin:latest
    ports:
    - 8081:8080
    volumes:
    - ${PROJECT_PATH}\rm-ticketing-admin\config.yaml:/app/config.yaml

  rm_ticketing_promoter:
    image: romarius75/rm-ticketing-promoter:latest
    ports:
    - 8082:8080
    volumes:
    - ${PROJECT_PATH}\rm-ticketing-promoter\config.yaml:/app/config.yaml

  rm_ticketing_page:
    image: romarius75/rm-ticketing-page:latest
    ports:
    - 8083:8080
    volumes:
    - ${PROJECT_PATH}\rm-ticketing-page\config.yaml:/app/config.yaml

  rm_ticketing_scanner:
    image: romarius75/rm-ticketing-scanner:latest
    ports:
    - 8084:8080
    volumes:
    - ${PROJECT_PATH}\rm-ticketing-scanner\config.yaml:/app/config.yaml

  rm_ticketing_tests:
    image: romarius75/rm-ticketing-tests:latest
    ports:
    - 8085:80
    volumes:
    - ${PROJECT_PATH}\rm-ticketing-tests\nginx-server.conf:/etc/nginx/conf.d/default.conf:ro
    - ${PROJECT_PATH}\rm-ticketing-tests\config.json:/usr/share/nginx/html/config.json

volumes:
  rm_ticketing_mysql_volume:
  rm_ticketing_node_volume:
